### ISSUE TITLE
[BUG] Can't disable break others voidchest

### ISSUE THREAD

**Issue by lackooka** [GeorgeV220/VoidChestAPI#16]
**Describe the bug**
I tried to disable breaking others voidchest with permission and config too and it is not working

**To Reproduce**
No permission to bypass (only permission have is voidchest.break.<chesttype>) and not owner can break any voidchest.

**Expected behavior**
You can break others voidchest

**Screenshots**
No available screeonshot.

**Server Information (please complete the following information):**
- Server version (`/bukkit:version`): 
- Current Purpur Version: 1.21-DEV-4e55e26 (MC: 1.21)*
* You are running the latest version
Previous: 1.21-2284-4e55e26 (MC: 1.21)
- Installed plugins (`/bukkit:plugins`): 
- WorldGuard Report Pastebin Link (`/wg report -p`): 
- https://paste.enginehub.org/bmOrsbi51.report

**Additional context**

**Comment by GeorgeV220** [comment]
Updade to the latest version (5.1.4)

**Comment by lackooka** [comment]
4.2.0 is the latest.
